"""Tests for stub / placeholder / fixture lead detector.

Covers:
- Domain-based detection (.example., .test., localhost)
- Fixture company name detection (StubCorp, TestCo, etc.)
- Email-based detection (@example., @stubcorp, @test.)
- Missing URL + synthetic note detection
- Canonical and legacy lead row classification
- Integration with lead scoring write path
- Integration with deeper research approval path
"""

from unittest.mock import MagicMock

from commission_crowd_agent.deeper_research import DeeperResearchService
from commission_crowd_agent.lead_scoring import LeadScorer, ScoreOutput
from commission_crowd_agent.stub_detector import classify_lead_row, is_placeholder_lead

# --- is_placeholder_lead unit tests ---


def test_example_domain_is_placeholder() -> None:
    assert is_placeholder_lead(source_url="https://acme-solutions.example.com")


def test_test_domain_is_placeholder() -> None:
    assert is_placeholder_lead(source_url="https://demo.test.internal")


def test_localhost_is_placeholder() -> None:
    assert is_placeholder_lead(source_url="http://localhost:8080")


def test_stubcorp_name_is_placeholder() -> None:
    assert is_placeholder_lead(company_name="StubCorp")


def test_stubcorp_lowercase_is_placeholder() -> None:
    assert is_placeholder_lead(company_name="stubcorp")


def test_valid_company_is_not_placeholder() -> None:
    assert not is_placeholder_lead(company_name="Acme Solutions", source_url="https://acme.com")


def test_example_email_is_placeholder() -> None:
    assert is_placeholder_lead(contact_email="alice@example.com")


def test_stubcorp_email_is_placeholder() -> None:
    assert is_placeholder_lead(contact_email="bob@stubcorp.com")


def test_no_hint_is_not_placeholder() -> None:
    assert not is_placeholder_lead(company_name="Real Corp", source_url="", contact_email="")


def test_missing_url_plus_stub_note_is_placeholder() -> None:
    assert is_placeholder_lead(source_url="", notes="this is a stub lead for testing")


def test_missing_url_plus_fixture_note_is_placeholder() -> None:
    assert is_placeholder_lead(source_url="", notes="fixture data generated by test suite")


def test_missing_url_plus_normal_note_is_not_placeholder() -> None:
    assert not is_placeholder_lead(source_url="", notes="strong signal from web search")


# --- classify_lead_row tests ---


def _canonical_lead_row(
    company: str = "Acme",
    url: str = "https://acme.com",
    email: str = "a@acme.com",
    notes: str = "",
) -> list[str]:
    """Build a 15-col canonical leads row."""
    return [
        "LID-001",  # 0 lead_id
        "2026-01-01",  # 1 created_at_utc
        "web_search",  # 2 source
        url,  # 3 source_url
        company,  # 4 company_name
        "Alice",  # 5 contact_name
        email,  # 6 contact_email
        "CEO",  # 7 role_title
        "SaaS",  # 8 market
        "US",  # 9 country
        "problem",  # 10 problem_signal
        "comm",  # 11 commission_signal
        "90",  # 12 fit_score
        "discovered",  # 13 status
        notes,  # 14 notes
    ]


def test_canonical_example_row_classified_placeholder() -> None:
    row = _canonical_lead_row(company="StubCorp", url="https://test.example.com")
    assert classify_lead_row(row) is True


def test_canonical_real_row_not_placeholder() -> None:
    row = _canonical_lead_row(company="Acme Solutions", url="https://acme.com")
    assert classify_lead_row(row) is False


def test_legacy_row_short_classified() -> None:
    """Legacy 9-col rows also get best-effort classification."""
    row = [
        "LID-OLD",
        "web_search",
        "Alice",
        "StubCorp",
        "https://fixture.example.com",
        "alice@example.com",
        "discovered",
        "2026-01-01",
        "notes here",
    ]
    assert classify_lead_row(row) is True


def test_very_short_row_safe() -> None:
    """Rows with fewer than 5 columns should not crash and return False."""
    assert classify_lead_row(["only", "two"]) is False


# --- Integration: lead_scoring writes ---


def test_placeholder_not_written_to_opportunities() -> None:
    """A score flagged as placeholder must not generate an opportunity row."""
    scorer = LeadScorer()
    mock_adapter = MagicMock()
    mock_adapter.validate_tab_header.return_value = {"ok": True}
    mock_adapter.append_row.return_value = {"ok": True}
    mock_adapter.read_last_rows.return_value = {"ok": True, "rows": []}

    scores = [
        ScoreOutput(
            lead_id="STUB-001",
            company_name="StubCorp",
            fit_score=90,
            confidence="high",
            reasons=["Has email"],
            missing_data=[],
            recommended_next_action="verify_email_then_draft_research",
            is_placeholder=True,
        )
    ]
    result = scorer.write_opportunities(scores, sheets_adapter=mock_adapter, dry_run=False)
    assert result["placeholder"] == 1
    assert result["placeholder_ids"] == ["STUB-001"]
    assert result["written"] == 0
    mock_adapter.append_row.assert_not_called()


def test_placeholder_not_created_for_deeper_research_approval() -> None:
    """A score flagged as placeholder must not generate a deeper-research approval."""
    scorer = LeadScorer()
    mock_gate = MagicMock()
    mock_adapter = MagicMock()
    mock_adapter.read_last_rows.return_value = {"ok": True, "rows": []}

    scores = [
        ScoreOutput(
            lead_id="STUB-001",
            company_name="StubCorp",
            fit_score=90,
            confidence="high",
            reasons=["Has email"],
            missing_data=[],
            recommended_next_action="verify_email_then_draft_research",
            is_placeholder=True,
        )
    ]
    results = scorer.request_deeper_research_approvals(
        scores, approval_gate=mock_gate, sheets_adapter=mock_adapter, dry_run=False
    )
    assert results == []
    mock_gate.create_approval.assert_not_called()


# --- Integration: deeper research service ---


def test_research_one_lead_detects_placeholder() -> None:
    """Research on a .example lead should set is_placeholder=True immediately."""
    svc = DeeperResearchService()
    result = svc.research_one_lead(
        lead_id="STUB-001",
        company_name="StubCorp",
        source_url="https://stubcorp.example.com",
    )
    assert result.is_placeholder is True
    assert "Placeholder fixture lead detected" in result.notes


def test_outreach_draft_approval_blocked_for_placeholder() -> None:
    """request_outreach_draft_approval must return BLOCKED for placeholder results."""
    svc = DeeperResearchService()
    result = svc.research_one_lead(
        lead_id="STUB-001",
        company_name="StubCorp",
        source_url="https://stubcorp.example.com",
    )
    assert result.is_placeholder is True

    gate = MagicMock()
    adapter = MagicMock()
    res = svc.request_outreach_draft_approval(
        result, approval_gate=gate, sheets_adapter=adapter, dry_run=False
    )
    assert res["approval_id"] == "BLOCKED"
    gate.create_approval.assert_not_called()


def test_real_lead_does_not_detect_placeholder() -> None:
    """A real company without fixture markers must not be flagged."""
    svc = DeeperResearchService()
    result = svc.research_one_lead(
        lead_id="REAL-001",
        company_name="Stripe",
        source_url="https://stripe.com",
    )
    assert result.is_placeholder is False
